import type { BrowserTemplate, Opts } from "./cli.js";

//esbuild writes its output into public/ alongside the handwritten
//index.html / manifest.json, so the generated files have to be listed
//one by one - the folder itself must stay tracked.
//
//expo is absent on purpose: it bundles with metro and has its own ignore
//file, see genExpoGitIgnore.ts
const OUTPUT: Record<BrowserTemplate, string[]> = {
    react: ["public/app.js", "public/app.css"],
    pwa: ["public/app.js", "public/app.css", "public/sw.js"],
    extension: [
        "public/popup.js",
        "public/popup.css",
        "public/content.js",
        "public/background.js",
    ],
};

//with --tailwind the stylesheet imported by the app is compiled from
//src/styles.css, so it stops being a source file and must not be committed
const TAILWIND_OUTPUT: Record<BrowserTemplate, string> = {
    react: "src/app.css",
    pwa: "src/app.css",
    extension: "src/popup.css",
};

export default function genGitIgnore(o: Opts) {
    const template = o.template as BrowserTemplate;

    const generated = [...OUTPUT[template], "public/*.map"];

    if (o.tailwind) {
        generated.push(TAILWIND_OUTPUT[template]);
    }

    const output = generated.join("\n");

    const tpl = `
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# esbuild output
${output}
`;

    return tpl;
}
